### ISSUE TITLE
Class Department Constructor error

### ISSUE THREAD

**Issue by PinkPig-cq** [aspnet/EntityFramework.Docs.zh-cn#19]
官方文档书写有误（codefirst代码演示），演示的实例。
在微软的官网的文档也有同样的错误（EF关系映射章节codefirst演示的代码）。
但不影响理解。
public class Department
{
   public Department()
   {
     this.Course = new HashSet<Course>(); 
     // Not this.Course but this.Courses
   }  
   public int DepartmentID { get; set; }
   public string Name { get; set; }
   public decimal Budget { get; set; }
   public DateTime StartDate { get; set; }
   public int? Administrator {get ; set; }
   public virtual ICollection<Course> Courses { get; set; }
}

**Comment by LisandroSu** [comment]
你好，@<参与者的 GITHUB 名称>，

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by LisandroSu** [comment]
你好，@PinkPig-cq

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@PinkPig-cq，
我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by PinkPig-cq** [comment]
> 官方文档书写有误（codefirst代码演示），演示的实例。
> 在微软的官网的文档也有同样的错误（EF关系映射章节codefirst演示的代码）。
> 但不影响理解。
> public class Department
> {
> public Department()
> {
> this.Course = new HashSet();
> // Not this.Course but this.Courses
> }
> public int DepartmentID { get; set; }
> public string Name { get; set; }
> public decimal Budget { get; set; }
> public DateTime StartDate { get; set; }
> public int? Administrator {get ; set; }
> public virtual ICollection Courses { get; set; }
> }



> 官方文档书写有误（codefirst代码演示），演示的实例。
> 在微软的官网的文档也有同样的错误（EF关系映射章节codefirst演示的代码）。
> 但不影响理解。
> public class Department
> {
> public Department()
> {
> this.Course = new HashSet();
> // Not this.Course but this.Courses
> }
> public int DepartmentID { get; set; }
> public string Name { get; set; }
> public decimal Budget { get; set; }
> public DateTime StartDate { get; set; }
> public int? Administrator {get ; set; }
> public virtual ICollection Courses { get; set; }
> }



> 你好，@PinkPig-cq，
> 我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
> 顺祝商祺！
> Microsoft DOCS 国际团队



> 你好，@PinkPig-cq
> 
> 我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
> 
> 顺祝商祺！
> Microsoft DOCS 国际团队
