### ISSUE TITLE
When did you via my pull?

### ISSUE THREAD

**Issue by HeMinzhang** [aspnet/EntityFramework.Docs.zh-cn#2]
When did you via my pull?

**Comment by CeciAc** [comment]
Hi @HeMinzhang 
Can you please provide more detail on this issue?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Closing this issue due lack of action item. 
Please feel free to create a new one or a PR if the issues persists

Kind regards,
Microsoft DOCS International Team
