### ISSUE TITLE
Suggestion:  we should not translate the name of special folder

### ISSUE THREAD

**Issue by personball** [aspnet/EntityFramework.Docs.zh-cn#22]
see https://github.com/aspnet/EntityFramework.Docs.zh-cn/commit/29b849d78f3e604383e5f49bef4af0cc003c9457#r31205300

**Comment by CeciAc** [comment]
Hello, @personball 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged in the PR you mention.
For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
