### ISSUE TITLE
Insert sequence issue

### ISSUE THREAD

**Issue by zxs731** [aspnet/EntityFramework.Docs.zh-cn#47]
i find if the child collection have item more than 20 then the insert sequence is not same with code. Not sure why and how to control the insert？

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback here https://developercommunity.visualstudio.com/spaces/61/index.html

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
