### ISSUE TITLE
中文翻译问题

### ISSUE THREAD

**Issue by htlsmilework** [aspnet/EntityFramework.Docs.zh-cn#48]
位置：https://docs.microsoft.com/zh-cn/ef/core/modeling/generated-properties#value-generated-on-add
原文：A property is considered to have a value assigned if it is not assigned the CLR default value (null for string, 0 for int, Guid.Empty for Guid, etc.). 
错误翻译： 属性被认为已赋值的前提是该属性未被赋予 CLR 默认值（string 的默认值为 null，int 的默认值为 0，Guid.Empty 的默认值为 Guid，等等)。
正确翻译：如果未为属性分配 CLR 默认值（string为 null, int 为 0, Guid 为Guid.Empty, 等等），则该属性被视为已赋值。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [生成的值的 EF Core](https://docs.microsoft.com/zh-cn/ef/core/modeling/generated-properties#value-generated-on-add)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by CeciAc** [comment]
你好，@htlsmilework 
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@htlsmilework

感谢你提交的语言方面的反馈。  

遗憾的是，我们语言团队评审你的反馈后，认为它不完全符合我们的接受条件，因为 [

  | 原有翻译中的逻辑体现的更加准确。
-- | --


] 

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福， 
Microsoft DOCS International Team
