### ISSUE TITLE
这个页面标黄色的代码无法正常显示。

### ISSUE THREAD

**Issue by tahen2** [aspnet/EntityFramework.Docs.zh-cn#50]
不仅仅是这个页面，有非常多的页面都是这一个问题。你们应该排查一下。我用的是chorme浏览器。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8d6f6f7b-b8d3-df80-33b7-46b0b98acd29
* Version Independent ID: 1a74a6d8-0ad4-9a22-d62e-1a2bab8b80b1
* Content: [最大长度-EF Core](https://docs.microsoft.com/zh-cn/ef/core/modeling/max-length#feedback)
* Content Source: [entity-framework/core/modeling/max-length.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/modeling/max-length.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by CeciAc** [comment]
你好，@tahen2
非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/aspnet/AspNetCore.Docs/issues/13143
因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
