### ISSUE TITLE
How and where to call this

### ISSUE THREAD

**Issue by huxiaozhong** [aspnet/EntityFramework.Docs.zh-cn#51]
How and where to call this: myDbContext.Database.Migrate();
give some example code please!!!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [迁移 - EF Core](https://docs.microsoft.com/zh-cn/ef/core/managing-schemas/migrations/#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by srvbpigh** [comment]
Hello, @huxiaozhong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/EntityFramework.Docs #1595](https://github.com/aspnet/EntityFramework.Docs/issues/1595) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @huxiaozhong

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/EntityFramework.Docs/issues/1595

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by DHclly** [comment]
> How and where to call this: myDbContext.Database.Migrate();
> give some example code please!!!
> 
> #### 文档详细信息
> ⚠ _请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。_
> 
> * ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
> * Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
> * Content: [迁移 - EF Core](https://docs.microsoft.com/zh-cn/ef/core/managing-schemas/migrations/#feedback)
> * Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/managing-schemas/migrations/index.md)
> * Product: **entity-framework**
> * Technology: **entity-framework-core**
> * GitHub Login: @bricelam
> * Microsoft Alias: **bricelam**

you can use it in function  `Main`   , @huxiaozhong 
```c#
using Microsoft.EntityFrameworkCore;
 public async static Task Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();
            AutoMigrationDb(host);
            await host.RunAsync();
        }
private static void AutoMigrationDb(IHost host)
        {
            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;
                try
                {
                    EFContext context = services.GetRequiredService<EFContext>();
                    context.Database.Migrate();
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogError(ex, "An error occurred migration the DB.");
                }
            }
        }
```
here is the demo : https://gitee.com/dhclly/IceDog.EFCore/blob/master/src/update-db/IceDog.UpdateDB.WebServer/Program.cs
