### ISSUE TITLE
使用了错误的句号"。"，应为英文“.”

### ISSUE THREAD

**Issue by depluin** [aspnet/EntityFramework.Docs.zh-cn#56]
4.更新适用于正在使用任何核心 EF 类型命名空间中使用了错误的句号

如
System.Data.EntityException = > System.Data**。**Entity.Core**。**EntityException

实际应为
System.Data.EntityException = > System.Data**.**Entity.Core**.**EntityException

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 73d5d89c-2648-4ce8-d5c3-4fb2371e6128
* Version Independent ID: 20e9f35b-8bb2-2bc0-c032-e4be1915997f
* Content: [升级到 Entity Framework 6](https://docs.microsoft.com/zh-cn/ef/ef6/what-is-new/upgrading-to-ef6)
* Content Source: [entity-framework/ef6/what-is-new/upgrading-to-ef6.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/ef6/what-is-new/upgrading-to-ef6.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by srvbpigh** [comment]
Hello, @depluin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @depluin
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/ef/ef6/what-is-new/upgrading-to-ef6

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
