### ISSUE TITLE
Include 查询结果中的关联数据为空， select 报错问题

### ISSUE THREAD

**Issue by luy710** [aspnet/EntityFramework.Docs.zh-cn#57]
[在此处输入反馈]
using (var context = new BloggingContext())
{
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
            .ThenInclude(post => post.Author)
                .ThenInclude(author => author.Photo)
        .Select(Blogs => new BlogsItem{
             Name = Blogs.Posts.Author.Name
         });
}
假设 Blogs Posts Author为1对1关系
Name = Blogs.Posts.Author.Name 如果Blogs.Posts 为空 或者Blogs.Posts.Author为空会报错，这种如何处理呢？
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [加载相关数据 - EF Core](https://docs.microsoft.com/zh-cn/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by srvbpigh** [comment]
Hello, @luy710
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by luy710** [comment]
Thank you very much




------------------ 原始邮件 ------------------
发件人: "srvbpigh"<notifications@github.com>; 
发送时间: 2019年9月16日(星期一) 中午11:56
收件人: "aspnet/EntityFramework.Docs.zh-cn"<EntityFramework.Docs.zh-cn@noreply.github.com>; 
抄送: "02.07"<364233272@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [aspnet/EntityFramework.Docs.zh-cn] Include 查询结果中的关联数据为空， select 报错问题 (#57)




Hello, @luy710
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.
 
Kind regards,
 Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@luy710
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
