### ISSUE TITLE
Some assemblies' names were replaced by system.exception

### ISSUE THREAD

**Issue by rabbitism** [aspnet/EntityFramework.Docs.zh-cn#59]
This page has an alive example:
"System.Diagnostics.Debug.WriteLine()" was replaced by "system.exception（）"by mistake. 

Another example: 
https://docs.microsoft.com/zh-cn/ef/ef6/what-is-new/upgrading-to-ef6 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ed83069f-39a8-e992-95f7-a8b41154b6f4
* Version Independent ID: 144fe168-080f-6557-e4b2-a18adb4b89ed
* Content: [日志记录-EF Core](https://docs.microsoft.com/zh-cn/ef/core/miscellaneous/logging?tabs=v3)
* Content Source: [entity-framework/core/miscellaneous/logging.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/miscellaneous/logging.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @rabbitism
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rabbitism 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**I can't find System.Diagnostics.Debug.WriteLine() in the original document**
 
Kind regards,
Microsoft DOCS International Team

**Comment by rabbitism** [comment]
> Hello, @rabbitism
>  
> We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
> 
> **I can't find System.Diagnostics.Debug.WriteLine() in the original document**
>  
> Kind regards,
> Microsoft DOCS International Team

https://docs.microsoft.com/zh-cn/ef/core/miscellaneous/logging?tabs=v3#other-applications
The third item in English is 
"Logs to a debugger monitor using System.Diagnostics.Debug.WriteLine().“
in Chinese it is 
"使用 system.exception （）将日志记录到调试器监视器。"

which is obviously not correct.

**Comment by rabbitism** [comment]
> Hello, @rabbitism
>  
> We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
> 
> **I can't find System.Diagnostics.Debug.WriteLine() in the original document**
>  
> Kind regards,
> Microsoft DOCS International Team

https://docs.microsoft.com/zh-cn/ef/ef6/what-is-new/upgrading-to-ef6#2-ensure-that-assembly-references-to-systemdataentitydll-are-removed

this title in English is 
"2. Ensure that assembly references to System.Data.Entity.dll are removed"
in Chinese it is 
"确保已删除对 system.exception 的程序集引用"

---
I think this is some kind of mapping error in auto translation or CAT, it is not human error.

**Comment by CeciAc** [comment]
Hello, @rabbitism

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rabbitism 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/ef/core/miscellaneous/logging?tabs=v3

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
