### ISSUE TITLE
Program Error

### ISSUE THREAD

**Issue by Turbokk** [aspnet/EntityFramework.Docs.zh-cn#60]
// Create -- Error
...
db.add().  
Need to change --> db.Blogs.add().

[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [入门 - EF Core](https://docs.microsoft.com/zh-cn/ef/core/get-started/?tabs=visual-studio#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @Turbokk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@tdykstra see [Create, read, update & delete](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=visual-studio#create-read-update--delete

```
using System;
using System.Linq;

namespace EFGetStarted
{
    class Program
    {
        static void Main()
        {
            using (var db = new BloggingContext())
            {
                // Create
                Console.WriteLine("Inserting a new blog");
                db.Add(new Blog { Url = "http://blogs.msdn.com/adonet" });
---------->
```

Looks like a bug to me.

Transfer this issue to the EF docs repo and we'll fix it.

**Comment by Rick-Anderson** [comment]
Actually, the code is correct. Please close this issue.

**Comment by CeciAc** [comment]
Closing this issue as per writer request

**Comment by Turbokk** [comment]
I’m Sorry,


I will check these problems several times in the future to ensure the effectiveness of the problem and feedback.


Thank you for your reply.

________________________________

**Comment by Rick-Anderson** [comment]
@Turbokk  no problem. At first glance I thought it was a bug too.
